# Generated by Django 5.2.4 on 2025-07-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_rename_title_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='edited_on',
            new_name='updated_on',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
