# Generated by Django 5.2.4 on 2025-07-27 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='categorySlug',
            field=models.SlugField(max_length=500, null=True),
        ),
    ]
