# Generated by Django 5.2.4 on 2025-07-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_category_slug_category_categoryslug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categorySlug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
