# Generated by Django 5.2.4 on 2025-07-27 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_category_post_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
